### ISSUE TITLE
run parseInt on skip and limit parameters

### ISSUE THREAD

**Issue by vquigley** [DennisAhaus/node-express-crud-router#12]
MongoDB 3.2 requires skip and limit to be numbers, so we must parse it internally.

express-restify-mongoose have a similar issue. https://github.com/florianholzapfel/express-restify-mongoose/pull/216

I was able to fix locally by updating controller.js lines to add parseInt

      var limit = parseInt(req.query.limit) || 25;
      var skip = parseInt(req.query.skip) || 0;

Sorry I cannot do a pull request.

**Comment by Zertz** [comment]
There you go!
